The ``say_my_name`` module
=============================

Using ``say_my_name``
------------------------

import the say_my_name function
>>> say_my_name = __import__('3-say_my_name').say_my_name

invalid variable string empty
>>> say_my_name(None, "Paula")
Traceback (most recent call last):
TypeError: first_name must be a string

invalid variable string empty
>>> say_my_name("Paula", None)
Traceback (most recent call last):
TypeError: last_name must be a string

invalid variable tupla
>>> say_my_name((1,), "Paula")
Traceback (most recent call last):
TypeError: first_name must be a string

invalid variable list
>>> say_my_name("Paula", [1, 2, 3])
Traceback (most recent call last):
TypeError: last_name must be a string

invalid variable list
>>> say_my_name([25, 45], "Paula")
Traceback (most recent call last):
TypeError: first_name must be a string

invalid variable tupla
>>> say_my_name("Paula", (1,))
Traceback (most recent call last):
TypeError: last_name must be a string

invalid variable negative number
>>> say_my_name("Paula", -70)
Traceback (most recent call last):
TypeError: last_name must be a string

invalid variable negative number
>>> say_my_name(-70, "Paula")
Traceback (most recent call last):
TypeError: first_name must be a string

invalid variable float number
>>> say_my_name("Paula", -7.0)
Traceback (most recent call last):
TypeError: last_name must be a string

invalid variable float number
>>> say_my_name(-7.0, "Paula")
Traceback (most recent call last):
TypeError: first_name must be a string

invalid variable positive floats
>>> say_my_name("Paula", 9.5)
Traceback (most recent call last):
TypeError: last_name must be a string

invalid variable positive floats
>>> say_my_name(9.5, "Paula")
Traceback (most recent call last):
TypeError: first_name must be a string

passin 0 arguments
>>> say_my_name()
Traceback (most recent call last)
TypeError: say_my_name() missing 1 required positional argument: 'first_name'